### ISSUE TITLE
How to set hostname

### ISSUE THREAD

**Issue by Babynini** [HugoFara/lwt-docker-installer#3]
After I installed into my Nas, the console output the log with "Could not reliably determine the server's fully qualified domain name, using 172.29.4.3. Set the 'ServerName' directive globally to suppress this message "

Then when I come to the website, it tells me that "Message: Host '172.29.4.3' is not allowed to connect to this MariaDB server]"

Maybe I set the wrong hostname in the docker-composer.yml?

This is how I set the yml file

```
version: "3.7"
services:
  web:
    image: ghcr.io/hugofara/lwt:master
    container_name: lwt
    depends_on:
      - db
    links:
      - db
    volumes:
      - /share/Container/lwtrhugofara/media:/var/www/html/media
    ports:
      - "38080:80"
    restart: unless-stopped
  db:
    container_name: lwt_db
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        MYSQL_ROOT_PASSWORD: "qwerty"
    hostname: db
    image: mariadb:10.7
    restart: unless-stopped
    volumes:
        - /share/Container/lwtrhugofara/sql:/var/lib/mysql
```

These are the messages I got.

![image](https://github.com/HugoFara/lwt-docker-installer/assets/25690791/8cf91b5c-43bc-47fc-a6ea-f8527f4c1d7a)

![image](https://github.com/HugoFara/lwt-docker-installer/assets/25690791/8e5bf260-6b19-4e22-9307-f6c032f1a297)

![image](https://github.com/HugoFara/lwt-docker-installer/assets/25690791/6f22b132-1024-4614-9c06-a0e61aa2a0e0)
